module.exports = Object.freeze({
  BLANK_FIELD: '--',

  LABEL_OPEN: 'Open',
  LABEL_HIGH: 'High',
  LABEL_LOW: 'Low',
  LABEL_MARKET_CAP: 'Mkt Cap',
  LABEL_VOLUME: 'Volume',
  LABEL_AVERAGE: 'Avg',
  LABEL_DIVIDEND: 'Div',
  LABEL_PE_RATIO: 'P/E Ratio',
  LABEL_ROE: 'ROE',
  LABEL_FCFY: 'FCFY',

  OPTIONAL_LABEL_EPS: 'eps',
  OPTIONAL_LABEL_DIVIDEND: '%',

  OPEN_VALUE_PRECISION: 2,
  HIGH_VALUE_PRECISION: 2,
  LOW_VALUE_PRECISION: 2,
  MARKET_CAP_VALUE_PRECISION: 0,
  VOLUME_VALUE_PRECISION: 0,
  DIVIDEND_VALUE_PRECISION: 2,
  PE_VALUE_PRECISION: 2,
  ROE_VALUE_PRECISION: 1,
  FCFY_VALUE_PRECISION: 1,
  EPS_VALUE_PRECISION: 2,

  VALUE_SUFFIX_ROE: '%',
  VALUE_SUFFIX_FCFY: '%',

  OPTIONAL_VALUE_SUFFIX_DIVIDEND: '%'
});